version: '3'

services:
  app:
    build:
      context: .
    tty: true
    volumes:
      - ./:/app
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm run dev"
    ports:
      - "80:3000"
